mutation PopulateDatabaseWithSeedData @auth(level: USER) {
  patient_insertMany(data: [
    {
      accountNumber: "12345",
      name: "John Doe",
      dateOfBirth: "1970-01-01"
      email: "john.doe@example.com",
      phone: "555-1212",
      address: "123 Main St"
    },
    {
      accountNumber: "67890",
      name: "Jane Smith",
      dateOfBirth: "1980-02-02"
      email: "jane.smith@example.com",
      phone: "555-1313",
      address: "456 Elm St"
    }
  ])
  pharmacy_insertMany(data: [
    {
      name: "Acme Pharmacy",
      address: "789 Oak St",
      email: "acme@example.com",
      phone: "555-1414"
    },
    {
      name: "Beta Pharmacy",
      address: "101 Pine St",
      email: "beta@example.com",
      phone: "555-1515"
    }
  ])
}